export enum CaseStatus {
  TOTAL_TICKETS = 'TOTAL_TICKETS',
  ESCALATED_TICKETS = 'ESCALATED_TICKETS',
  REOPEN_TICKETS = 'REOPEN_TICKETS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  PENDING_TICKETS = 'PENDING_TICKETS',
  PENDING_WITH_OTHERS = 'PENDING_WITH_OTHERS',
  PENDING_WITH_CUSTOMER = 'PENDING_WITH_CUSTOMER',
  PENDING_WITH_BILLDESK = 'PENDING_WITH_BILLDESK',
  PENDING_WITH_CAMS = 'PENDING_WITH_CAMS'
}

export const WorkflowStatuses = [
  CaseStatus.PENDING_TICKETS,
  CaseStatus.PENDING_WITH_OTHERS,
  CaseStatus.PENDING_WITH_CUSTOMER,
  CaseStatus.PENDING_WITH_BILLDESK,
  CaseStatus.PENDING_WITH_CAMS,
  CaseStatus.RESOLVED,
  CaseStatus.CLOSED,
  CaseStatus.REOPEN_TICKETS,
  CaseStatus.ESCALATED_TICKETS
] as const;
