export enum RoleCode {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CASE_CREATOR = 'CASE_CREATOR',
  CASE_ASSIGNEE = 'CASE_ASSIGNEE',
  SUPERVISOR = 'SUPERVISOR',
  MANAGER = 'MANAGER',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  AUDITOR = 'AUDITOR',
  CUSTOMER_SUPPORT_AGENT = 'CUSTOMER_SUPPORT_AGENT',
  PROXY_USER = 'PROXY_USER',
  END_CUSTOMER = 'END_CUSTOMER'
}
